### PR TITLE
I18n - Update for German translations

### PR DESCRIPTION
**Pull request by scento**
This pull request fixes several typos in the German translations and replaces some English strings in `values-de/` with the German equivalents. In case it is intended to keep the English vocabulary, please comment on this pull request and I'll remove possibly misleading translations.

### CODE REVIEW

**Comment by mlewe** [comment]
It's rather hard to decide. I would take the translation of the git book (http://git-scm.com/book/de/v1) to be canonical. This would mean that several terms like commit, push, branch, etc. are not to be translated.
At least thats what I tried to follow in my translation.

**Comment by scento** [comment]
Okay, I adapted my request according to the recommendations of @mlewe.

**Comment by mlewe** [comment]
Looks good to me. :+1:

**Comment by maks** [comment]
merged in 4d441acbb76af10b5b03a26e5620afc23ee1661d
thank you for your contribution @scento and review by @mlewe

**Pull request closed without merging**
