### PR TITLE
Add gradle build script.

### PR DESCRIPTION
**Pull request by mlewe**
This would be useful for people using Android Studio.

### CODE REVIEW

**Comment by mlewe** [comment]
I have made a few more changes.

**Comment by d10** [comment]
Thanks, @mlewe, I can't merge them now, probably next week.

**Comment by mlewe** [comment]
While importing the project in Android Studio you should be able to specify that you want to use the default gradle wrapper.

The repository block is present in the file:
```gradle
repositories {
    jcenter()
}
```

Oh, and one more thing, make sure you have installed the support library and support library repository option in the Android SDK. You can do so, either by using the SDK updater or on the command line
```
echo 'y' | android -s update sdk -f -u -a -t extra-android-support,extra-android-m2repository
```

**Comment by d10** [comment]
Thanks so much, @mlewe!

**Pull request closed without merging**
